import Head from 'next/head';
import { CSSReset } from '../src/components/CSSReset';
import Footer from './home/Footer';
import Header from './home/Header';
import Menu from './home/Menu';
import TimeLine from './home/TimeLine';

export default function Home() {
  return (
    <div>
      <CSSReset />
      <Head>
        <title>AluraTube</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu />
      <Header />
      <TimeLine />
      <Footer />
    </div>
  );
}
